version: "3"

services:
  app:
    image: node:19
    working_dir: /var/www/node
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped
    volumes:
      - .:/var/www/node
    ports:
      - "8080:8080"
    environment:
      - ENV=${ENV}